# General args
seed: 1234321
dont_print_args: false
cuda: true
device_num: 2
train_data_pct: 0.9
val_data_pct: 0.01
seq_len: 15
do_test: false
do_valid: true
valid_epochs: 20
train_epochs: 1000

# Model args
rnn_type: LSTM
hidden_size: 128
finetune: true
dropout: 0.3
num_layers: 2
masked_lm: false
vocab_size: 29
save_epochs: 20

# Data args
data_path: data/moocs/mooc.csv
batch_size: 4096

# Training args not needed here
# Evaluation arguments not needed here
# Sampling arguments are provided by the testing script explicitly
disable_tqdm: true

# Sampling args
estimate_type: search
proposal_func: lm
interp_func: linear
top_k: 0
top_p: 0
num_beams: 0.85
num_mc_samples: 10000
sub_estimates: []
total_seq_len: 20
hist_len: 18
excluded_terms: [1]


