# General args
seed: 1234321
dont_print_args: false
cuda: true
device_num: 5
train_data_pct: 0.9
val_data_pct: 0.05
seq_len: 100
do_test: false

# Model args
rnn_type: LSTM
hidden_size: 128
dropout: 0.3
num_layers: 2
masked_lm: false
checkpoint_path: models/shakespeare/shakespeare_model.pt

# Training args not needed here
# Evaluation arguments not needed here
# Sampling arguments are provided by the testing script explicitly
disable_tqdm: false


