
# MOOCs
checkpoint_path: /home/showalte/research/prob_seq_queries/models/moocs/
device_num: 7
hidden_size: 128
vocab_size: 98
val_data_pct: 0.01
seq_len: 15
data_path: data/moocs/mooc.csv

# # Amazon
# checkpoint_path: /home/showalte/research/prob_seq_queries/models/amazon/
# device_num: 7
# hidden_size: 512
# vocab_size: 30
# val_data_pct: 0.0001
# seq_len: 15
# data_path: /srv/disk00/samshow/amazon/amazon_text_dict.pkl

# # Apps
# checkpoint_path: /home/showalte/research/prob_seq_queries/models/apps/
# data_path: data/apps/lsapp.tsv
# hidden_size: 512
# seq_len: 15
# device_num: 2
# vocab_size: 88
# val_data_pct: 0.001

# General args
seed: 1234321
dont_print_args: False
cuda: true
train_data_pct: 0.9
do_test: false
do_valid: true
valid_epochs: 1

# Model args
rnn_type: LSTM
finetune: false
dropout: 0.3
num_layers: 2
masked_lm: false
val_metrics: ['accuracy']

# Data args
batch_size: 2048

# Training args not needed here
# Evaluation arguments not needed here
# Sampling arguments are provided by the testing script explicitly
disable_tqdm: true

# Sampling args
estimate_type: sample
proposal_func: lm
interp_func: linear
top_k: 0
top_p: 0
num_beams: 0.85
num_mc_samples: 10000
sub_estimates: []
total_seq_len: 20
hist_len: 18
excluded_terms: [1]


